/*
 * Licensed to the Fintech Open Source Foundation (FINOS) under one or
 * more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * FINOS licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id "com.google.protobuf"
    id "java-library"
    id "idea"
}

apply from: "${rootProject.projectDir.path}/gradle/base-java.gradle"

description = "TRAC D.A.P. metadata library, contains data structures for the TRAC metadata model"

// Using the Gradle Protobuf plugin with its default configuration
// Generate Java code and set up generated source sets
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$proto_version"
    }
}

dependencies {

    // Core protobuf for Java
    api "com.google.protobuf:protobuf-java"
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    compileOnly("com.diffblue.cover:cover-annotations:1.6.0")
    testImplementation("com.diffblue.cover:cover-annotations:1.6.0")

}

// Javadoc gives a lot of warnings on the protobuf generated code
// Turn these warnings off, they're noisy and obscure real Javadoc warnings from TRAC's own code
tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
}

allprojects {
  afterEvaluate {
    plugins.withId('jacoco') {
      jacocoTestReport {
        classDirectories.setFrom(
          files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
              'org/finos/tracdap/metadata/ArrayValue.class',
              'org/finos/tracdap/metadata/ArrayValue$Builder.class',
              'org/finos/tracdap/metadata/BasicType.class',
              'org/finos/tracdap/metadata/Common.class',
              'org/finos/tracdap/metadata/CopyStatus.class',
              'org/finos/tracdap/metadata/Custom.class',
              'org/finos/tracdap/metadata/CustomDefinition.class',
              'org/finos/tracdap/metadata/CustomDefinition$Builder.class',
              'org/finos/tracdap/metadata/Data.class',
              'org/finos/tracdap/metadata/DataDefinition.class',
              'org/finos/tracdap/metadata/DataDefinition$Builder.class',
              'org/finos/tracdap/metadata/DataDefinition$Delta.class',
              'org/finos/tracdap/metadata/DataDefinition$Delta$Builder.class',
              'org/finos/tracdap/metadata/DataDefinition$Part.class',
              'org/finos/tracdap/metadata/DataDefinition$Part$Builder.class',
              'org/finos/tracdap/metadata/DataDefinition$Snap.class',
              'org/finos/tracdap/metadata/DataDefinition$Snap$Builder.class',
              'org/finos/tracdap/metadata/DateValue.class',
              'org/finos/tracdap/metadata/DateValue$Builder.class',
              'org/finos/tracdap/metadata/DatetimeValue.class',
              'org/finos/tracdap/metadata/DatetimeValue$Builder.class',
              'org/finos/tracdap/metadata/DecimalValue.class',
              'org/finos/tracdap/metadata/DecimalValue$Builder.class',
              'org/finos/tracdap/metadata/ExportDataJob.class',
              'org/finos/tracdap/metadata/ExportDataJob$Builder.class',
              'org/finos/tracdap/metadata/FieldSchema.class',
              'org/finos/tracdap/metadata/FieldSchema$Builder.class',
              'org/finos/tracdap/metadata/File.class',
              'org/finos/tracdap/metadata/FileDefinition.class',
              'org/finos/tracdap/metadata/FileDefinition$Builder.class',
              'org/finos/tracdap/metadata/FileType.class',
              'org/finos/tracdap/metadata/FileType$Builder.class',
              'org/finos/tracdap/metadata/Flow.class',
              'org/finos/tracdap/metadata/FlowDefinition.class',
              'org/finos/tracdap/metadata/FlowDefinition$Builder.class',
              'org/finos/tracdap/metadata/FlowEdge.class',
              'org/finos/tracdap/metadata/FlowEdge$Builder.class',
              'org/finos/tracdap/metadata/FlowNode.class',
              'org/finos/tracdap/metadata/FlowNode$Builder.class',
              'org/finos/tracdap/metadata/FlowNodeType.class',
              'org/finos/tracdap/metadata/FlowSocket.class',
              'org/finos/tracdap/metadata/FlowSocket$Builder.class',
              'org/finos/tracdap/metadata/ImportDataJob.class',
              'org/finos/tracdap/metadata/ImportDataJob$Builder.class',
              'org/finos/tracdap/metadata/ImportModelJob.class',
              'org/finos/tracdap/metadata/ImportModelJob$Builder.class',
              'org/finos/tracdap/metadata/IncarnationStatus.class',
              'org/finos/tracdap/metadata/Job.class',
              'org/finos/tracdap/metadata/JobDefinition.class',
              'org/finos/tracdap/metadata/JobDefinition$Builder.class',
              'org/finos/tracdap/metadata/JobGroup.class',
              'org/finos/tracdap/metadata/JobGroup$Builder.class',
              'org/finos/tracdap/metadata/JobGroupType.class',
              'org/finos/tracdap/metadata/JobStatusCode.class',
              'org/finos/tracdap/metadata/JobType.class',
              'org/finos/tracdap/metadata/LogicalExpression.class',
              'org/finos/tracdap/metadata/LogicalExpression$Builder.class',
              'org/finos/tracdap/metadata/LogicalOperator.class',
              'org/finos/tracdap/metadata/MapValue.class',
              'org/finos/tracdap/metadata/MapValue$Builder.class',
              'org/finos/tracdap/metadata/MetadataFormat.class',
              'org/finos/tracdap/metadata/MetadataVersion.class',
              'org/finos/tracdap/metadata/Model.class',
              'org/finos/tracdap/metadata/ModelDefinition.class',
              'org/finos/tracdap/metadata/ModelDefinition$Builder.class',
              'org/finos/tracdap/metadata/ModelInputSchema.class',
              'org/finos/tracdap/metadata/ModelInputSchema$Builder.class',
              'org/finos/tracdap/metadata/ModelOutputSchema.class',
              'org/finos/tracdap/metadata/ModelOutputSchema$Builder.class',
              'org/finos/tracdap/metadata/ModelParameter.class',
              'org/finos/tracdap/metadata/ModelParameter$Builder.class',
              'org/finos/tracdap/metadata/ModelType.class',
              'org/finos/tracdap/metadata/ObjectDefinition.class',
              'org/finos/tracdap/metadata/ObjectDefinition$Builder.class',
              'org/finos/tracdap/metadata/ObjectId.class',
              'org/finos/tracdap/metadata/ObjectProtoWrapper.class',
              'org/finos/tracdap/metadata/ObjectType.class',
              'org/finos/tracdap/metadata/ParallelJobGroup.class',
              'org/finos/tracdap/metadata/ParallelJobGroup$Builder.class',
              'org/finos/tracdap/metadata/PartKey.class',
              'org/finos/tracdap/metadata/PartKey$Builder.class',
              'org/finos/tracdap/metadata/PartType.class',
              'org/finos/tracdap/metadata/Resource.class',
              'org/finos/tracdap/metadata/ResourceType.class',
              'org/finos/tracdap/metadata/ResultDefinition.class',
              'org/finos/tracdap/metadata/ResultDefinition$Builder.class',
              'org/finos/tracdap/metadata/RunFlowJob.class',
              'org/finos/tracdap/metadata/RunFlowJob$Builder.class',
              'org/finos/tracdap/metadata/RunModelJob.class',
              'org/finos/tracdap/metadata/RunModelJob$Builder.class',
              'org/finos/tracdap/metadata/SchemaDefinition.class',
              'org/finos/tracdap/metadata/SchemaDefinition$Builder.class',
              'org/finos/tracdap/metadata/SchemaType.class',
              'org/finos/tracdap/metadata/Search.class',
              'org/finos/tracdap/metadata/SearchExpression.class',
              'org/finos/tracdap/metadata/SearchExpression$Builder.class',
              'org/finos/tracdap/metadata/SearchOperator.class',
              'org/finos/tracdap/metadata/SearchParameters.class',
              'org/finos/tracdap/metadata/SearchParameters$Builder.class',
              'org/finos/tracdap/metadata/SearchTerm.class',
              'org/finos/tracdap/metadata/SearchTerm$Builder.class',
              'org/finos/tracdap/metadata/SequentialJobGroup.class',
              'org/finos/tracdap/metadata/SequentialJobGroup$Builder.class',
              'org/finos/tracdap/metadata/Storage.class',
              'org/finos/tracdap/metadata/StorageCopy.class',
              'org/finos/tracdap/metadata/StorageCopy$Builder.class',
              'org/finos/tracdap/metadata/StorageDefinition.class',
              'org/finos/tracdap/metadata/StorageDefinition$Builder.class',
              'org/finos/tracdap/metadata/StorageIncarnation.class',
              'org/finos/tracdap/metadata/StorageIncarnation$Builder.class',
              'org/finos/tracdap/metadata/StorageItem.class',
              'org/finos/tracdap/metadata/StorageItem$Builder.class',
              'org/finos/tracdap/metadata/StructField.class',
              'org/finos/tracdap/metadata/StructField$Builder.class',
              'org/finos/tracdap/metadata/StructSchema.class',
              'org/finos/tracdap/metadata/StructSchema$Builder.class',
              'org/finos/tracdap/metadata/TableSchema.class',
              'org/finos/tracdap/metadata/TableSchema$Builder.class',
              'org/finos/tracdap/metadata/Tag.class',
              'org/finos/tracdap/metadata/Tag$Builder.class',
              'org/finos/tracdap/metadata/TagHeader.class',
              'org/finos/tracdap/metadata/TagHeader$Builder.class',
              'org/finos/tracdap/metadata/TagOperation.class',
              'org/finos/tracdap/metadata/TagOuterClass.class',
              'org/finos/tracdap/metadata/TagSelector.class',
              'org/finos/tracdap/metadata/TagSelector$Builder.class',
              'org/finos/tracdap/metadata/TagUpdate.class',
              'org/finos/tracdap/metadata/TagUpdate$Builder.class',
              'org/finos/tracdap/metadata/TagUpdateOuterClass.class',
              'org/finos/tracdap/metadata/TenantInfo.class',
              'org/finos/tracdap/metadata/TenantInfo$Builder.class',
              'org/finos/tracdap/metadata/Type.class',
              'org/finos/tracdap/metadata/TypeDescriptor.class',
              'org/finos/tracdap/metadata/TypeDescriptor$Builder.class',
              'org/finos/tracdap/metadata/Value.class',
              'org/finos/tracdap/metadata/Value$Builder.class',
            ])
          })
        )
      }
    }
  }
}
