/*
 * Licensed to the Fintech Open Source Foundation (FINOS) under one or
 * more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * FINOS licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id "com.google.protobuf"
    id "java-library"
    id "idea"
}

apply from: "${rootProject.projectDir.path}/gradle/base-java.gradle"

description = "TRAC D.A.P. platform API, contains service API definitions for the TRAC platform services"

protobuf {

    protoc {
        artifact = "com.google.protobuf:protoc:$proto_version"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpc_version}"
        }
    }

    generateProtoTasks {

        all().configureEach { task ->

            task.builtins {
                java {}
            }

            task.plugins {
                grpc {}
            }
        }
    }
}

dependencies {

    // Core services API uses gRPC / Protobuf stubs
    api "io.grpc:grpc-stub"
    api "io.grpc:grpc-protobuf"
    api "com.google.protobuf:protobuf-java"

    api project(":tracdap-api-metadata")

    // Google APIs framework for REST APIs
    // Do not pull in the JavaX annotation API (it has an incompatible license)
    api (group: 'com.google.api.grpc', name: 'grpc-google-common-protos', version: "$gapi_version") {
        exclude group: "javax.annotation", module: "javax.annotation-api"
    }

    // JavaX "Generated" annotation is still required by gRPC generated code
    implementation project(':tracdap-lib-annotations')
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    compileOnly("com.diffblue.cover:cover-annotations:1.6.0")
    testImplementation("com.diffblue.cover:cover-annotations:1.6.0")

}

// Javadoc gives a lot of warnings on the protobuf generated code
// Turn these warnings off, they're noisy and obscure real Javadoc warnings from TRAC's own code
tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
}

allprojects {
  afterEvaluate {
    plugins.withId('jacoco') {
      jacocoTestReport {
        classDirectories.setFrom(
          files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
              'org/finos/tracdap/api/ClientConfigRequest.class',
              'org/finos/tracdap/api/ClientConfigRequest$Builder.class',
              'org/finos/tracdap/api/ClientConfigResponse.class',
              'org/finos/tracdap/api/ClientConfigResponse$Builder.class',
              'org/finos/tracdap/api/DataReadRequest.class',
              'org/finos/tracdap/api/DataReadRequest$Builder.class',
              'org/finos/tracdap/api/DataReadResponse.class',
              'org/finos/tracdap/api/DataReadResponse$Builder.class',
              'org/finos/tracdap/api/DataServiceProto.class',
              'org/finos/tracdap/api/DataWriteRequest.class',
              'org/finos/tracdap/api/DataWriteRequest$Builder.class',
              'org/finos/tracdap/api/DownloadRequest.class',
              'org/finos/tracdap/api/DownloadRequest$Builder.class',
              'org/finos/tracdap/api/DownloadResponse.class',
              'org/finos/tracdap/api/DownloadResponse$Builder.class',
              'org/finos/tracdap/api/ErrorDetailsProto.class',
              'org/finos/tracdap/api/FileReadRequest.class',
              'org/finos/tracdap/api/FileReadRequest$Builder.class',
              'org/finos/tracdap/api/FileReadResponse.class',
              'org/finos/tracdap/api/FileReadResponse$Builder.class',
              'org/finos/tracdap/api/FileWriteRequest.class',
              'org/finos/tracdap/api/FileWriteRequest$Builder.class',
              'org/finos/tracdap/api/JobRequest.class',
              'org/finos/tracdap/api/JobRequest$Builder.class',
              'org/finos/tracdap/api/JobStatus.class',
              'org/finos/tracdap/api/JobStatus$Builder.class',
              'org/finos/tracdap/api/JobStatusRequest.class',
              'org/finos/tracdap/api/JobStatusRequest$Builder.class',
              'org/finos/tracdap/api/ListResourcesRequest.class',
              'org/finos/tracdap/api/ListResourcesRequest$Builder.class',
              'org/finos/tracdap/api/ListResourcesResponse.class',
              'org/finos/tracdap/api/ListResourcesResponse$Builder.class',
              'org/finos/tracdap/api/ListTenantsRequest.class',
              'org/finos/tracdap/api/ListTenantsRequest$Builder.class',
              'org/finos/tracdap/api/ListTenantsResponse.class',
              'org/finos/tracdap/api/ListTenantsResponse$Builder.class',
              'org/finos/tracdap/api/MetadataBatchRequest.class',
              'org/finos/tracdap/api/MetadataBatchRequest$Builder.class',
              'org/finos/tracdap/api/MetadataBatchResponse.class',
              'org/finos/tracdap/api/MetadataBatchResponse$Builder.class',
              'org/finos/tracdap/api/MetadataGetRequest.class',
              'org/finos/tracdap/api/MetadataGetRequest$Builder.class',
              'org/finos/tracdap/api/MetadataReadRequest.class',
              'org/finos/tracdap/api/MetadataReadRequest$Builder.class',
              'org/finos/tracdap/api/MetadataSearchRequest.class',
              'org/finos/tracdap/api/MetadataSearchRequest$Builder.class',
              'org/finos/tracdap/api/MetadataSearchResponse.class',
              'org/finos/tracdap/api/MetadataSearchResponse$Builder.class',
              'org/finos/tracdap/api/MetadataServiceProto.class',
              'org/finos/tracdap/api/MetadataWriteBatchRequest.class',
              'org/finos/tracdap/api/MetadataWriteBatchRequest$Builder.class',
              'org/finos/tracdap/api/MetadataWriteBatchResponse.class',
              'org/finos/tracdap/api/MetadataWriteBatchResponse$Builder.class',
              'org/finos/tracdap/api/MetadataWriteRequest.class',
              'org/finos/tracdap/api/MetadataWriteRequest$Builder.class',
              'org/finos/tracdap/api/OrchestratorServiceProto.class',
              'org/finos/tracdap/api/PlatformInfoRequest.class',
              'org/finos/tracdap/api/PlatformInfoRequest$Builder.class',
              'org/finos/tracdap/api/PlatformInfoResponse.class',
              'org/finos/tracdap/api/PlatformInfoResponse$Builder.class',
              'org/finos/tracdap/api/ResourceInfoRequest.class',
              'org/finos/tracdap/api/ResourceInfoRequest$Builder.class',
              'org/finos/tracdap/api/ResourceInfoResponse.class',
              'org/finos/tracdap/api/ResourceInfoResponse$Builder.class',
              'org/finos/tracdap/api/TracDataApiGrpc$1.class',
              'org/finos/tracdap/api/TracDataApiGrpc$2.class',
              'org/finos/tracdap/api/TracDataApiGrpc$3.class',
              'org/finos/tracdap/api/TracDataApiGrpc$4.class',
              'org/finos/tracdap/api/TracDataApiGrpc$AsyncService.class',
              'org/finos/tracdap/api/TracDataApiGrpc$MethodHandlers.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiBaseDescriptorSupplier.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiBlockingStub.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiBlockingV2Stub.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiFileDescriptorSupplier.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiFutureStub.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiImplBase.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiMethodDescriptorSupplier.class',
              'org/finos/tracdap/api/TracDataApiGrpc$TracDataApiStub.class',
              'org/finos/tracdap/api/TracErrorDetails.class',
              'org/finos/tracdap/api/TracErrorDetails$Builder.class',
              'org/finos/tracdap/api/TracErrorItem.class',
              'org/finos/tracdap/api/TracErrorItem$Builder.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$1.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$2.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$3.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$4.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$AsyncService.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$MethodHandlers.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiBaseDescriptorSupplier.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiBlockingStub.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiBlockingV2Stub.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiFileDescriptorSupplier.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiFutureStub.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiImplBase.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiMethodDescriptorSupplier.class',
              'org/finos/tracdap/api/TracMetadataApiGrpc$TracMetadataApiStub.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$1.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$2.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$3.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$4.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$AsyncService.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$MethodHandlers.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiBaseDescriptorSupplier.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiBlockingStub.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiBlockingV2Stub.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiFileDescriptorSupplier.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiFutureStub.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiImplBase.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiMethodDescriptorSupplier.class',
              'org/finos/tracdap/api/TracOrchestratorApiGrpc$TracOrchestratorApiStub.class',
              'org/finos/tracdap/api/internal/MetadataTrustedProto.class',
              'org/finos/tracdap/api/internal/RuntimeJobInfoRequest.class',
              'org/finos/tracdap/api/internal/RuntimeJobInfoRequest$Builder.class',
              'org/finos/tracdap/api/internal/RuntimeJobResult.class',
              'org/finos/tracdap/api/internal/RuntimeJobResult$Builder.class',
              'org/finos/tracdap/api/internal/RuntimeJobStatus.class',
              'org/finos/tracdap/api/internal/RuntimeJobStatus$Builder.class',
              'org/finos/tracdap/api/internal/RuntimeListJobsRequest.class',
              'org/finos/tracdap/api/internal/RuntimeListJobsRequest$Builder.class',
              'org/finos/tracdap/api/internal/RuntimeListJobsResponse.class',
              'org/finos/tracdap/api/internal/RuntimeListJobsResponse$Builder.class',
              'org/finos/tracdap/api/internal/RuntimeServiceProto.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$1.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$2.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$3.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$4.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$AsyncService.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$MethodHandlers.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiBaseDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiBlockingStub.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiBlockingV2Stub.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiFileDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiFutureStub.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiImplBase.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiMethodDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TracRuntimeApiGrpc$TracRuntimeApiStub.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$1.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$2.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$3.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$4.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$AsyncService.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$MethodHandlers.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiBaseDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiBlockingStub.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiBlockingV2Stub.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiFileDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiFutureStub.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiImplBase.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiMethodDescriptorSupplier.class',
              'org/finos/tracdap/api/internal/TrustedMetadataApiGrpc$TrustedMetadataApiStub.class',
            ])
          })
        )
      }
    }
  }
}
